$(document).ready(function(){
	// alert("hey");

	$(".shoes_madden").hover(function(){
		$(".shoes_madden_name").toggle();
	})
	$(".shoes_puma").hover(function(){
		$(".shoes_puma_name").toggle();
	})
	$(".toliet_paper").hover(function(){
		$(".toliet_paper_name").toggle();
	})
	$(".umbrella").hover(function(){
		$(".umbrella_name").toggle();
	})
	$(".soap").hover(function(){
		$(".soap_name").toggle();
	})
	$(".beer").hover(function(){
		$(".beer_name").toggle();
	})
	$(".cream").hover(function(){
		$(".cream_name").toggle();
	})
	$(".eggs").hover(function(){
		$(".eggs_name").toggle();
	})
	$(".cream_cheese").hover(function(){
		$(".cream_cheese_name").toggle();
	})
	$(".beef").hover(function(){
		$(".beef_name").toggle();
	})
	$(".tobleron").hover(function(){
		$(".tobleron_name").toggle();
	})
	$(".rosemary").hover(function(){
		$(".rosemary_name").toggle();
	})
	$(".thyme").hover(function(){
		$(".thyme_name").toggle();
	})
	$(".flatbread").hover(function(){
		$(".flatbread_name").toggle();
	})
	$(".basil").hover(function(){
		$(".basil_name").toggle();
	})
	$(".lettuce").hover(function(){
		$(".lettuce_name").toggle();
	})
	$(".grapes").hover(function(){
		$(".grapes_name").toggle();
	})
	$(".swimmers").hover(function(){
		$(".swimmers_name").toggle();
	})
	$(".bofo").hover(function(){
		$(".bofo_name").toggle();
	})
	$(".rigatoni").hover(function(){
		$(".rigatoni_name").toggle();
	})
	$(".pepper").hover(function(){
		$(".pepper_name").toggle();
	})
	$(".onion").hover(function(){
		$(".onion_name").toggle();
	})
	$(".bacon").hover(function(){
		$(".bacon_name").toggle();
	})
	$(".peppers").hover(function(){
		$(".peppers_name").toggle();
	})
	$(".blueberries").hover(function(){
		$(".blueberries_name").toggle();
	})
	$(".garlic").hover(function(){
		$(".garlic_name").toggle();
	})
	$(".lemons").hover(function(){
		$(".lemons_name").toggle();
	})
	$(".cucumber").hover(function(){
		$(".cucumber_name").toggle();
	})
	$(".cat_food").hover(function(){
		$(".cat_food_name").toggle();
	})
	$(".almonds").hover(function(){
		$(".almonds_name").toggle();
	})
	$(".vitamins").hover(function(){
		$(".vitamins_name").toggle();
	})
	$(".rice").hover(function(){
		$(".rice_name").toggle();
	})
	$(".peanut_butter").hover(function(){
		$(".peanut_butter_name").toggle();
	})
	$(".cereal").hover(function(){
		$(".cereal_name").toggle();
	})
	$(".syrup").hover(function(){
		$(".syrup_name").toggle();
	})
	$(".oatmeal").hover(function(){
		$(".oatmeal_name").toggle();
	})
	$(".salmon").hover(function(){
		$(".salmon_name").toggle();
	})
	$(".waffle").hover(function(){
		$(".waffle_name").toggle();
	})
	$(".book").hover(function(){
		$(".book_name").toggle();
	})


// 	$('.items div').hover(function(){
//    $(this).siblings('.folder-hover').toggle();
// });
})