$(document).ready(function(){
	// alert("hey");

	$(".shoes_madden").hover(function(){
		$(".shoes_madden_name").toggle();
	})
	$(".shoes_puma").hover(function(){
		$(".shoes_puma_name").toggle();
	})
	$(".toliet_paper").hover(function(){
		$(".toliet_paper_name").toggle();
	})
	$(".umbrella").hover(function(){
		$(".umbrella_name").toggle();
	})
	$(".soap").hover(function(){
		$(".soap_name").toggle();
	})
	$(".beer").hover(function(){
		$(".beer_name").toggle();
	})
	$(".cream").hover(function(){
		$(".cream_name").toggle();
	})
	$(".eggs").hover(function(){
		$(".eggs_name").toggle();
	})
	$(".cream_cheese").hover(function(){
		$(".cream_cheese_name").toggle();
	})
	$(".beef").hover(function(){
		$(".beef_name").toggle();
	})
})